spring.application.name=quan_ly_sv
server.port=8080

# Đã sửa thành localhost chỉ vào máy của bạn
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager
spring.datasource.username=sa
spring.datasource.password=123123

spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect